(define (lexer-read-nodes! lexer)
  (define (open-brac? c) (char=? c #\[))
  (let loop ()
    (when (char-alphabetic? (lexer-cur lexer))
      (lexer-read-ident!      lexer)
      (lexer-skip-whitespace! lexer)
      (lexer-expect!          lexer colon?)
      (lexer-add-tok!         lexer '(colon ()))
      (lexer-skip-whitespace! lexer)
      (lexer-read-ident!      lexer)
      (lexer-skip-whitespace! lexer)
      (lexer-expect!          lexer open-brac?)
      (lexer-add-tok!         lexer '(open-bracket ()))
      (lexer-read-edges!      lexer)
      (lexer-skip-whitespace! lexer)
      (loop))))

